# Generated by Django 5.1.4 on 2025-01-16 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_avatar_vehicle_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='brand',
            new_name='drive',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='drive_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='image',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='power_volume',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='myapp.brand'),
        ),
    ]
