# Generated by Django 5.1.4 on 2025-01-16 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_brand_rename_brand_vehicle_drive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.avatar'),
        ),
    ]
